"""init

Revision ID: 6b851f5d0314
Revises: b70b6a935685
Create Date: 2023-12-02 13:54:31.043142

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6b851f5d0314"
down_revision: Union[str, None] = "b70b6a935685"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
