"""init

Revision ID: 8ae4705f92b3
Revises: 
Create Date: 2023-11-30 20:08:45.644951

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ae4705f92b3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_transaction",
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tx_hash", sa.String(length=255), nullable=False),
        sa.Column("tx_from", sa.String(length=255), nullable=False),
        sa.Column("tx_to", sa.String(length=255), nullable=False),
        sa.Column("tx_value", sa.BigInteger(), nullable=True),
        sa.Column("tx_fee", sa.BigInteger(), nullable=True),
        sa.Column("tx_input", sa.Text(), nullable=True),
        sa.Column("gas_price", sa.BigInteger(), nullable=False),
        sa.Column("gas_limit", sa.Integer(), nullable=False),
        sa.Column("gas_used", sa.BigInteger(), nullable=True),
        sa.Column("nonce", sa.Integer(), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("replaced_by", sa.String(length=255), nullable=True),
        sa.Column("confirmation_count", sa.Integer(), nullable=False),
        sa.Column("confirmation_need", sa.Integer(), nullable=False),
        sa.Column("contract_method", sa.String(length=255), nullable=True),
        sa.Column("parsed_input", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("base_fee_per_gas", sa.Integer(), nullable=True),
        sa.Column("max_fee_per_gas", sa.Integer(), nullable=True),
        sa.Column("max_priority_fee_per_gas", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "settings",
        sa.Column("transaction_confirmation_count", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "wallet",
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("index"),
    )
    op.create_table(
        "system_transaction",
        sa.Column("origin_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("direction", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["raw_transaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("origin_id"),
        sa.UniqueConstraint("wallet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_transaction")
    op.drop_table("wallet")
    op.drop_table("user")
    op.drop_table("settings")
    op.drop_table("raw_transaction")
    # ### end Alembic commands ###
