"""init

Revision ID: 6902df372906
Revises: 6e7864049002
Create Date: 2023-12-02 13:56:41.240623

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6902df372906"
down_revision: Union[str, None] = "6e7864049002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("system_transaction_origin_id_key", "system_transaction", type_="unique")
    op.drop_constraint("system_transaction_wallet_id_key", "system_transaction", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "system_transaction_wallet_id_key", "system_transaction", ["wallet_id"]
    )
    op.create_unique_constraint(
        "system_transaction_origin_id_key", "system_transaction", ["origin_id"]
    )
    # ### end Alembic commands ###
