"""init

Revision ID: 6e7864049002
Revises: 6b851f5d0314
Create Date: 2023-12-02 13:54:56.100087

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e7864049002"
down_revision: Union[str, None] = "6b851f5d0314"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("raw_transaction", "raw", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("raw_transaction", "raw", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
