"""init

Revision ID: b70b6a935685
Revises: 5d85d3b7b718
Create Date: 2023-11-30 20:10:58.489860

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b70b6a935685"
down_revision: Union[str, None] = "5d85d3b7b718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("raw_transaction", "tx_value", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("raw_transaction", "gas_price", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("raw_transaction", "max_fee_per_gas", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column(
        "raw_transaction", "max_priority_fee_per_gas", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_transaction", "max_priority_fee_per_gas", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column("raw_transaction", "max_fee_per_gas", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("raw_transaction", "gas_price", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("raw_transaction", "tx_value", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
